# Generated by Django 3.2.8 on 2021-10-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_b',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_c',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_d',
            new_name='D',
        ),
    ]
