# Generated by Django 3.2.8 on 2021-10-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20211016_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='A',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='B',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='C',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='D',
            field=models.CharField(max_length=200),
        ),
    ]
